/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Escritor */

#ifndef _Included_Escritor
#define _Included_Escritor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Escritor
 * Method:    setChar
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Escritor_setChar
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
