/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class submarino_Submarino */

#ifndef _Included_submarino_Submarino
#define _Included_submarino_Submarino
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     submarino_Submarino
 * Method:    getChar
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_submarino_Submarino_getChar
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
